# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests on multiple devices"
  lane :tests do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(devices: ["iPhone 8", "iPhone 13 Pro Max", "iPad Pro (9.7-inch)"],
              scheme: "EZ Recipes")
  end
  
  desc "Upload a new build to the App Store"
  lane :release do
    capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "EZ Recipes")
    upload_to_app_store                  # upload your app to App Store Connect
  end
end
