# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests on a specified device"
  lane :test do |options|
    # Swift package CI recommendations: https://developer.apple.com/documentation/xcode/building-swift-packages-or-apps-that-use-them-in-continuous-integration-workflows
    # Resolve package dependencies: xcodebuild -resolvePackageDependencies -scheme EZ\ Recipes -project ./EZ\ Recipes.xcodeproj -disableAutomaticPackageResolution
    # Show build settings: xcodebuild -showBuildSettings -scheme EZ\ Recipes -project ./EZ\ Recipes.xcodeproj -disableAutomaticPackageResolution
    # Disable 'Slide to Type' on each simulator: /usr/libexec/PlistBuddy -c "Add :KeyboardContinuousPathEnabled bool false" ~/Library/Developer/CoreSimulator/Devices/84CA0B87-356F-4160-A3E7-5AC636BEF880/data/Library/Preferences/com.apple.keyboard.ContinuousPath.plist >/dev/null 2>&1
    # Build project & run unit and UI tests on all simulators: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme EZ\ Recipes -project ./EZ\ Recipes.xcodeproj -derivedDataPath ~/Library/Developer/Xcode/DerivedData/EZ_Recipes-cuhmoxzpybdazjcsljkgfvxmyeud -destination 'platform=iOS Simulator,id=ACCE5FA5-142E-4DDB-89D5-18BD949644EC' -destination 'platform=iOS Simulator,id=AD55AFA8-4014-406B-996D-58BD6548F72A' -destination 'platform=iOS Simulator,id=DDD5015F-9C9F-434F-9454-3748C749A432' clean build test | tee '~/Library/Logs/scan/EZ Recipes-EZ Recipes.log' | xcbeautify
    run_tests(scheme: "EZ Recipes",
              device: options[:device],
              clean: true,
              xcodebuild_formatter: "xcbeautify",
              output_types: "junit",
              disable_package_automatic_updates: true)
  end
  
  desc "Generate screenshots for the App Store"
  lane :screenshots do
    # Resolve package dependencies: xcodebuild -resolvePackageDependencies -scheme EZ\ Recipes -project ./EZ\ Recipes.xcodeproj
    # Show build settings: xcodebuild -showBuildSettings -scheme EZ\ Recipes -project ./EZ\ Recipes.xcodeproj
    # For each device
    # Wait for the simulator to fully boot: xcrun simctl bootstatus ACCE5FA5-142E-4DDB-89D5-18BD949644EC -b &> /dev/null
    # Override the status bar: xcrun simctl status_bar ACCE5FA5-142E-4DDB-89D5-18BD949644EC override --time 2007-01-09T09:41:00-05:00 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --operatorName '' --cellularBars 4 --batteryState charged --batteryLevel 100 &> /dev/null
    # Clean, build, test the app, & take screenshots on all devices: set -o pipefail && xcodebuild -scheme EZ\ RecipesUITests -project ./EZ\ Recipes.xcodeproj -derivedDataPath /var/folders/w4/jz5wfy_511g5r2q6t6qm3nc9hk7wqj/T/snapshot_derived20230102-59844-z0fp12 -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.1' -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=16.1' -destination 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=16.1' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US clean build test | tee ~/Library/Logs/snapshot/EZ\ RecipesUITests-EZ\ RecipesUITests.log | xcbeautify
    # Clear status bar override: xcrun simctl status_bar ACCE5FA5-142E-4DDB-89D5-18BD949644EC clear &> /dev/null
    capture_screenshots
    frame_screenshots
  end
  
  desc "Upload a new build to the App Store"
  lane :release do
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "EZ Recipes")
    upload_to_app_store                  # upload your app to App Store Connect
  end
end
