# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "macos-14"

    strategy:
      fail-fast: false
      matrix:
        # Escape spaces and parentheses in the device string
        device: ["'iPhone SE (3rd generation)'", "'iPhone 15 Pro Max'", "'iPad Pro (11-inch) (4th generation)'"]

    defaults:
      run:
        working-directory: "./EZ Recipes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: bundle install

      - name: Install xcbeautify & xcodes
        run: |
          brew install xcbeautify
          brew install xcodesorg/made/xcodes
    
       - name: Install yeetd for faster test performance
         run: |
           wget https://github.com/biscuitehh/yeetd/releases/download/1.0/yeetd-normal.pkg
           sudo installer -pkg yeetd-normal.pkg -target /
           yeetd &

      - name: Run Tests
        run: bundle exec fastlane ios test device:${{ matrix.device }}
