# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: "macos-14"

    strategy:
      fail-fast: false
      matrix:
        # Escape spaces and parentheses in the device string
        device: ["'iPhone SE (3rd generation)'", "'iPhone 15 Pro Max'", "'iPad Pro (11-inch) (4th generation)'"]

    defaults:
      run:
        working-directory: "./EZ Recipes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: bundle install

      - name: Install xcbeautify
        run: brew install xcbeautify
    
      - name: Install xcodes
        run: brew install xcodesorg/made/xcodes

      - name: Run Tests
        run: bundle exec fastlane ios test device:${{ matrix.device }}
