# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        # Escape spaces and parentheses in the device string
        # Use supported simulators: https://github.com/actions/runner-images
        device: ["'iPhone SE (3rd generation)'", "'iPhone 16 Pro Max'", "'iPad Pro 11-inch (M4)'"]

    defaults:
      run:
        working-directory: "./EZ Recipes"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fastlane
        run: bundle install

      - name: Install xcbeautify
        run: |
          brew install xcbeautify

      - name: Run Tests
        run: bundle exec fastlane ios test device:${{ matrix.device }}
