# Automate testing & deployment using Fastlane
name: Fastlane

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: './EZ Recipes'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Fastlane
        run: bundle install
    
      - name: Install xcbeautify
        run: brew install xcbeautify
    
      - name: Run Tests
        run: bundle exec fastlane ios tests
